# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        # name our first filter set "squared_thumbnail_medium" for example
        squared_thumbnail_medium:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [300, 300]
                    mode: outband
                    allow_upscale: true

        # name our first filter set "squared_thumbnail_small" for example
        squared_thumbnail_small:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [200, 200]
                    mode: outband
                    allow_upscale: true